server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou2
    username: root
    password: wyh1997210
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.179.130
    username: leyou
    password: leyou
    virtual-host: /leyou
  redis:
      host: 192.168.179.130
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    prefer-ip-address: true
    ip-address: 127.0.0.1
mybatis:
  type-aliases-package: com.leyou.user.pojo