server:
  port: 8084
spring:
  application:
    name: goods-web
  thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      cache: false
  rabbitmq:
    host: 192.168.179.130
    username: leyou
    password: leyou
    virtual-host: /leyou
  mvc:
      static-path-pattern: /**
  resources:
      static-locations: classpath:/static/
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期